title: "扎克爱思 | 技术博客 | 个人成长"
email: zach.thinking@gmail.com
description: >- 
  专注于分享软件开发、技术趋势、个人成长和创新思考。涵盖编程、职业发展、技术洞察和生活感悟。
keywords: "软件开发, 技术博客, 程序员, 个人成长, 职业发展"
baseurl: "" 
url: "https://zachthinking.github.io"
github_username: zachthinking

# 网站图标配置
favicon: /favicon.ico
logo: /assets/images/favicon-128x128.png

# SEO 优化配置
author: "Zach"
lang: "zh-CN"
google_site_verification: ""  # Google Search Console
baidu_site_verification: ""   # 百度站长工具

# Open Graph / 社交媒体
social:
  name: zachthinking
  links:
    - https://github.com/zachthinking
    - https://twitter.com/zachthinking  # 如果有 Twitter 账号

# 文章默认图片
default_post_image: "/assets/images/default-post.jpg"

# 性能和SEO插件
markdown: kramdown
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-last-modified-at

# Jekyll SEO Tag 配置
twitter:
  username: zachthinking
  card: summary_large_image

facebook:
  app_id: ""  # 如果有 Facebook 应用，填写这里
  publisher: ""
  admins: ""

# 网站结构化数据
schema:
  "@type": "WebSite"
  name: "扎克爱思的技术博客"
  alternateName: "Zach's Tech Blog"
  url: "https://zachthinking.github.io"

# Google Analytics配置
jekyll_analytics:
  GoogleAnalytics:          # 使用 GoogleAnalytics
    id: G-ZM7KN1DZ25        # 替换为您的跟踪ID
    anonymizeIp: false      # 是否匿名化IP
