name: Jekyll Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Jekyll site
      uses: actions/jekyll-build-pages@v1
      env:
        JEKYLL_ENV: production
